//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTovar
    {
        public int IDOrder { get; set; }
        public string Articul { get; set; }
        public Nullable<double> Count { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Tovar Tovar { get; set; }
    }
}
