//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.OrderTovar = new HashSet<OrderTovar>();
        }
    
        public int IDOrder { get; set; }
        public Nullable<System.DateTime> DateOrder { get; set; }
        public Nullable<System.DateTime> DateDilivery { get; set; }
        public Nullable<int> AddressDilivery { get; set; }
        public Nullable<int> IDUser { get; set; }
        public Nullable<double> COD { get; set; }
        public string Status { get; set; }
    
        public virtual Addresses Addresses { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<OrderTovar> OrderTovar { get; set; }
    }
}
