//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public Tovar()
        {
            this.OrderTovar = new HashSet<OrderTovar>();
        }
    
        public string Articul { get; set; }
        public string Name { get; set; }
        public string UI { get; set; }
        public Nullable<double> Cost { get; set; }
        public string Supplier { get; set; }
        public string Creator { get; set; }
        public string Category { get; set; }
        public Nullable<double> Sale { get; set; }
        public Nullable<double> Count { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }

        public double? CostNew
        {
            get
            {
                return (Sale > 0) ? (Cost - (Cost * (Sale / 100))) : Cost;
            }
        }

        public string Cvet1
        {
            get
            {
                return (Sale > 15) ? "#2E8B57" : "white";
            }
        }
        public string Cvet2
        {
            get
            {
                return (Count == 0) ? "Cyan" : null;
            }
        }
        public string Linia
        {
            get
            {
                return (Sale > 0) ? "Strikethrough" : "None";
            }
        }
        public string Vidno
        {
            get
            {
                return (Sale != 0) ? "Visible" : "Hidden";
            }
        }
        public string Krasn
        {
            get
            {
                return (Sale > 0) ? "Red" : "Black";
            }
        }

        public virtual Categories Categories { get; set; }
        public virtual ICollection<OrderTovar> OrderTovar { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual UIes UIes { get; set; }
    }
}
