//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UIes
    {
        public UIes()
        {
            this.Tovar = new HashSet<Tovar>();
        }
    
        public string UI { get; set; }
    
        public virtual ICollection<Tovar> Tovar { get; set; }
    }
}
