//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public int IDOrder { get; set; }
        public Nullable<System.DateTime> DateDilivery { get; set; }
        public string FIO { get; set; }
        public string Status { get; set; }
        public Nullable<double> Cost { get; set; }
    }
}
